flask_app/accueillants/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectMultipleField
from wtforms.validators import DataRequired


class AccueillantInfoForm(FlaskForm):
    disponibilite = StringField('Disponibilité')
    nom = StringField('Nom', validators=[DataRequired()])
    tel = StringField('Téléphone')
    adresse = StringField('Adresse')
    email = StringField('Email')
    accueillis = SelectMultipleField(u'Accueilli', choices=[])
    next_action = TextAreaField('Prochaine Action')
    remarques = TextAreaField('Remarques')
    submit = SubmitField("OK")


class SendMailForm(FlaskForm):
    body = TextAreaField('Message', validators=[DataRequired()])
    object_ = StringField('Objet', validators=[DataRequired()])
    destinataire = StringField('Destinataire', validators=[DataRequired()])
    destinataire_copie = StringField('CC')
    submit = SubmitField('Envoyer')

flask_app/boucles_accueil/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectField
from wtforms.validators import DataRequired
from wtforms.fields.html5 import DateField


class AccueilliInfoForm(FlaskForm):
    nom = StringField('Nom', validators=[DataRequired()])
    tel = StringField('Téléphone')
    email = StringField('Email')
    next_action = TextAreaField('Prochaine action')
    remarques = TextAreaField('Remarques')
    submit = SubmitField("OK")


class NewAccueilForm(FlaskForm):
    date_debut = DateField(
        'Début', format="%Y-%m-%d")
    date_fin = DateField(
        'Fin', format="%Y-%m-%d")
    accueillant = SelectField(u'Accueillant', coerce=int)
    remarque = TextAreaField('Remarque')
    submit = SubmitField("OK")

flask_app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_mail import Mail

from env import APP_CONFIG_SECRET_KEY, LOP_PASS, LOP_LOGIN, LOP_HOST

mail_settings = {
    "MAIL_SERVER": LOP_HOST,
    "MAIL_PORT": 465,
    "MAIL_USE_TLS": False,
    "MAIL_USE_SSL": True,
    "MAIL_USERNAME": LOP_LOGIN,
    "MAIL_PASSWORD": LOP_PASS,
    "MAIL_DEFAULT_SENDER": LOP_LOGIN
}

app = Flask(__name__)
app.config['SECRET_KEY'] = APP_CONFIG_SECRET_KEY
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///site.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config.update(mail_settings)
db = SQLAlchemy(app)
bcrypt = Bcrypt(app)
login_manager = LoginManager(app)
mail = Mail(app)
login_manager.login_view = 'coordinateurs.login'
login_manager.login_message_category = 'info'

from flask_app.main.routes import main
from flask_app.boucles_accueil.routes import boucles_accueil
from flask_app.coordinateurs.routes import coordinateurs
from flask_app.accueillants.routes import accueillants

app.register_blueprint(main)
app.register_blueprint(boucles_accueil)
app.register_blueprint(coordinateurs)
app.register_blueprint(accueillants)

flask_app/accueillants/routes.py
import re

from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_required
from flask_mail import Message
from bs4 import BeautifulSoup as soup

from env import GOOGLE_APP_CREDS
from flask_app import db, mail, bcrypt
from flask_app.models import Accueillant, Email_OP, Accueilli, Coordinateur
from flask_app.accueillants.forms import SendMailForm, AccueillantInfoForm
from flask_app.accueillants.utils_mailer import get_mail_from_last, get_conversations, send_email_simple, connect_to_drive


accueillants = Blueprint('accueillants', '__name__')


@accueillants.route('/liste_accueillants')
@login_required
def liste_accueillants():
    liste_accueillants = Accueillant.query.all()
    dict_emails = get_conversations(Email_OP.query.distinct())
    return render_template('liste_accueillants.html',
                           accueillants=liste_accueillants,
                           emails=dict_emails,
                           title="Accueillants")


@accueillants.route('/email_accueillant/<int:acc_id>', methods=['GET', 'POST'])
@login_required
def email_accueillant(acc_id):
    acc = Accueillant.query.get_or_404(acc_id)
    dict_emails = get_conversations(Email_OP.query.distinct())
    form = SendMailForm()
    if form.validate_on_submit():
        emails_re = "([a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+)"
        recipients = re.findall(emails_re, "florian.dadouchi@gmail.com")
        recipients = list(map(str.lower, recipients))
        cc = re.findall(emails_re, form.destinataire_copie.data)
        cc = list(map(str.lower, cc))
        msg = Message(subject=form.object_.data,
                      body=form.body.data,
                      recipients=recipients,
                      cc=cc)
        mail.send(msg)
        return redirect(url_for('accueillants.liste_accueillants')+f"#{acc.id}")
    elif request.method == 'GET':
        form.destinataire.data = acc.email
    return render_template('email_accueillant.html',
                           accueillant=acc,
                           emails=dict_emails,
                           title="Accueillants",
                           form=form)


@accueillants.route('/accueillant/new', methods=['GET', 'POST'])
@login_required
def new_accueillant():
    form = AccueillantInfoForm()
    accueillis = Accueilli.query.all()

    if form.validate_on_submit():
        accueillant = Accueillant(disponibilite=form.disponibilite.data,
                                  nom=form.nom.data,
                                  tel=form.tel.data,
                                  adresse=form.adresse.data,
                                  email=form.email.data,
                                  next_action=form.next_action.data,
                                  remarques=form.remarques.data)

        values = request.form.getlist('check')
        list_acc = [Accueilli.query.get(v) for v in values]
        accueillant.accueillis.extend(list_acc)
        db.session.add(accueillant)
        db.session.commit()
        flash('Accueillant créé', 'success')
        return redirect(url_for('accueillants.liste_accueillants'))
    return render_template('accueillant_infos.html',
                           title='create_modif_accueillant',
                           legend='Nouvel Accueillant',
                           form=form,
                           accueillant=None,
                           accueillis=accueillis)


@accueillants.route('/accueillant/<int:acc_id>', methods=['GET', 'POST'])
@login_required
def update_accueillant(acc_id):
    acc = Accueillant.query.get_or_404(acc_id)
    form = AccueillantInfoForm()
    accueillis = Accueilli.query.all()

    if form.validate_on_submit():
        acc.nom = form.nom.data
        acc.tel = form.tel.data
        acc.adresse = form.adresse.data
        acc.email = form.email.data
        acc.next_action = form.next_action.data
        acc.remarques = form.remarques.data
        values = request.form.getlist('check')
        list_acc = [Accueilli.query.get(v) for v in values]
        acc.accueillis = list_acc
        db.session.commit()
        return redirect(url_for('accueillants.liste_accueillants')+f"#{acc.id}")
    elif request.method == 'GET':
        form.nom.data = acc.nom
        form.tel.data = acc.tel
        form.adresse.data = acc.adresse
        form.email.data = acc.email
        form.next_action.data = acc.next_action
        form.remarques.data = acc.remarques
        list_to_check = [a.id for a in acc.accueillis]

    return render_template('accueillant_infos.html',
                           title='create_modif_accueillant',
                           legend='Modifier les Infos',
                           form=form,
                           accueillant=acc,
                           accueillis=accueillis,
                           list_to_check=list_to_check)


@accueillants.route('/accueillant/<int:acc_id>/delete', methods=['POST'])
@login_required
def delete_accueillant(acc_id):
    acc = Accueillant.query.get_or_404(acc_id)
    db.session.delete(acc)
    db.session.commit()
    flash(f'Accueillant "{acc.nom}" enlevé de la liste', 'success')
    return redirect(url_for('accueillants.liste_accueillants'))


#######################
# Pour la mise en route
#######################

@accueillants.route('/synchronize', methods=['GET', 'POST'])
def synchronize():
    # Add the admin
    hashed_password = bcrypt.generate_password_hash("admin").decode('utf-8')
    coordo = Coordinateur(
        nom="admin", email="admin@admin.org", password=hashed_password)
    db.session.add(coordo)
    db.session.commit()

    # Get the data
    credentials = GOOGLE_APP_CREDS
    client = connect_to_drive(credentials)
    coordo_sheet = client.open(
        "flask-Coordo/Mediation").worksheet("Accueillants")
    liste_accueillants_raw = coordo_sheet.get_all_values()

    # Handle poorly formatted emails
    emails_re = "([a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+)"
    tel_re = "([0-9][0-9])"
    liste_accueillants_to_add = \
        [Accueillant(
            disponibilite=row[0],
            nom=row[1].title(),
            tel=''.join("; " if i % 15 == 0 else char for i, char in enumerate(
                ".".join(re.findall(tel_re, row[2])), 1)),
            adresse=row[3],
            email="; ".join(re.findall(emails_re, row[4])).lower(),
            next_action=row[5],
            remarques=row[6])
            for i, row in enumerate(liste_accueillants_raw) if i > 1]

    for acc in liste_accueillants_to_add:
        try:
            db.session.add(acc)
            db.session.commit()
        except:
            db.session.close()

    return redirect(url_for('accueillants.liste_accueillants'))


@accueillants.route('/synchronize_email')
@login_required
def synchronize_email():
    mails_roundcube = get_mail_from_last(180)

    for m in mails_roundcube:
        # Remove the replies
        dom = soup(m.body_, 'html.parser')
        quote = dom.find_all("div", class_="gmail_quote") \
            + dom.findAll('blockquote')  \
            + dom.findAll("div", class_='yahoo_quoted')  \
            + dom.findAll("div", class_='x_gmail_quote') \
            + dom.findAll('div', attrs={"data-marker": "__QUOTED_TEXT__"}) \
            + dom.findAll('div', attrs={"data-marker": "__HEADERS__"}) \
            + dom.findAll('div', attrs={"data-marker": "__SIG_PRE__"})

        for tag in quote:
            try:
                tag.decompose()
            except:
                pass

        # Update body
        m.body_ = str(dom)

    mail_dict = get_conversations(mails_roundcube)
    for liste_emails in mail_dict.values():
        for mail in liste_emails:
            try:
                db.session.add(mail)
                db.session.commit()
            except:
                db.session.close()

    return render_template('index.html', mails=mail_dict, title="Index")

flask_app/boucles_accueil/routes.py
from flask import render_template, url_for, flash, redirect, Blueprint
from flask_login import login_required
from flask_app import db
from flask_app.models import Accueilli, Accueillant, Email_OP, Sejour
from flask_app.boucles_accueil.forms import AccueilliInfoForm, NewAccueilForm
from flask_app.accueillants.utils_mailer import get_conversations
from flask_app.accueillants.forms import SendMailForm
from sqlalchemy import desc

boucles_accueil = Blueprint('boucles_accueil', '__name__')


@boucles_accueil.route('/boucle/<int:acc_id>', methods=['GET', 'POST'])
@login_required
def boucle(acc_id):
    accueilli = Accueilli.query.get_or_404(acc_id)
    sejours = (Sejour.query.filter_by(accueilli_id=accueilli.id)
                           .order_by(desc("date_debut"))
                           .all())

    dict_emails = get_conversations(Email_OP.query.distinct())
    liste_accueillants = Accueillant.query.filter(
        Accueillant.id.in_([a.id for a in accueilli.accueillants])).all()
    form = NewAccueilForm(obj=accueilli)
    form.accueillant.choices = [(acc.id, acc.nom)
                                for acc in liste_accueillants]
    if form.validate_on_submit():
        new_sejour = Sejour(accueilli_id=accueilli.id,
                            accueillant_id=form.accueillant.data,
                            date_debut=form.date_debut.data,
                            date_fin=form.date_fin.data,
                            remarque=form.remarque.data)
        db.session.add(new_sejour)
        db.session.commit()
        return redirect(url_for('boucles_accueil.boucle', acc_id=accueilli.id))
    return render_template('boucle.html',
                           accueilli=accueilli,
                           form=form,
                           emails=dict_emails,
                           sejours=sejours)


@boucles_accueil.route('/liste_boucles')
@login_required
def liste_boucles():
    accueillis = Accueilli.query.all()
    liste_accueillants = Accueillant.query.all()
    return render_template('liste_boucles.html', accueillis=accueillis,
                           accueillants=liste_accueillants)


@boucles_accueil.route('/accueilli/new', methods=['GET', 'POST'])
@login_required
def new_accueilli():
    form = AccueilliInfoForm()
    if form.validate_on_submit():
        accueilli = Accueilli(nom=form.nom.data,
                              email=form.email.data,
                              tel=form.tel.data,
                              remarques=form.remarques.data)
        db.session.add(accueilli)
        db.session.commit()
        flash(f'Accueilli créé : {accueilli.nom}', 'success')
        return redirect(url_for('boucles_accueil.liste_boucles'))
    return render_template('accueilli_infos.html',
                           title='create_modif_accueilli',
                           legend='Nouvel Accueilli',
                           form=form)


@boucles_accueil.route('/accueilli/update', methods=['GET', 'POST'])
@login_required
def update_accueilli():
    # form = AccueilliInfoForm()
    # if form.validate_on_submit():
    #     accueilli = Accueilli(nom=form.nom.data,
    #                           email=form.email.data,
    #                           tel=form.tel.data,
    #                           remarques=form.remarques.data)
    #     db.session.add(accueilli)
    #     db.session.commit()
    #     flash(f'Accueilli créé : {accueilli.nom}', 'success')
    #     return redirect(url_for('boucles_accueil.liste_accueillis'))
    return render_template('liste_boucles.html',
                           title='modif_accueilli',
                           legend='Update Accueilli')


@boucles_accueil.route('/email_accueilli/<int:acc_id>', methods=['GET', 'POST'])
@login_required
def email_accueilli(acc_id):
    acc = Accueilli.query.get_or_404(acc_id)
    dict_emails = get_conversations(Email_OP.query.distinct())
    form = SendMailForm()
    if form.validate_on_submit():
        emails_re = "([a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+)"
        recipients = re.findall(emails_re, "florian.dadouchi@gmail.com")
        recipients = list(map(str.lower, recipients))
        cc = re.findall(emails_re, form.destinataire_copie.data)
        cc = list(map(str.lower, cc))
        msg = Message(subject=form.object_.data,
                      body=form.body.data,
                      recipients=recipients,
                      cc=cc)
        mail.send(msg)
        return redirect(url_for('boucles_accueil.liste_boucles')+f"#{acc.id}")
    elif request.method == 'GET':
        form.destinataire.data = acc.email
    return render_template('email_accueillant.html',
                           accueillant=acc,
                           emails=dict_emails,
                           title="Accueillants",
                           form=form)

flask_app/main/routes.py
from flask import Blueprint, render_template

main = Blueprint('main', '__name__')


@main.route('/')
def index():
    return render_template('index.html')


@main.route('/about')
def about():
    return render_template('base.html')


@main.route('/about2')
def about2():
    return render_template('about2.html')

flask_app/templates/accueillant_infos.html
{% extends "layout_logged_in.html" %}

{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <div class="en-tete form-row">
                <legend class="border-bottom mb-4"> {{ legend }}</legend>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    {{ form.nom.label(class="form-control-label") }}
                    {% if form.nom.errors %}
                    {{ form.nom(class="form-control form-control-sm is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.nom.errors %}
                        <span>{{ error }}</span>
                        {% endfor%}
                    </div>
                    {% else %}
                    {{ form.nom(class="form-control form-control-sm") }}
                    {% endif %}
                </div>
                <div class="form-group col-md-6">
                    {{ form.tel.label(class="form-control-label") }}
                    {% if form.tel.errors %}
                    {{ form.tel(class="form-control form-control-sm is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.tel.errors %}
                        <span>{{ error }}</span>
                        {% endfor%}
                    </div>
                    {% else %}
                    {{ form.tel(class="form-control form-control-sm") }}
                    {% endif %}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-sm is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                        {% endfor%}
                    </div>
                    {% else %}
                    {{ form.email(class="form-control form-control-sm") }}
                    {% endif %}
                </div>
                <div class="form-group col-md-6">
                    {{ form.disponibilite.label(class="form-control-label") }}
                    {% if form.disponibilite.errors %}
                    {{ form.disponibilite(class="form-control form-control-sm is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.disponibilite.errors %}
                        <span>{{ error }}</span>
                        {% endfor%}
                    </div>
                    {% else %}
                    {{ form.disponibilite(class="form-control form-control-sm") }}
                    {% endif %}
                </div>
            </div>

            <div class="form-group">
                {{ form.adresse.label(class="form-control-label") }}
                {% if form.adresse.errors %}
                {{ form.adresse(class="form-control form-control-sm is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.adresse.errors %}
                    <span>{{ error }}</span>
                    {% endfor%}
                </div>
                {% else %}
                {{ form.adresse(class="form-control form-control-sm") }}
                {% endif %}
            </div>

            <div class="form-group ">
                {{ form.accueillis.label(class="form-control-label") }}
                <div class="mycheckbox">
                    {% for accueilli in accueillis %}
                    {% if accueilli.id in list_to_check %}
                    <div class="custom-control custom-checkbox ">
                        <input type="checkbox" name="check" value={{accueilli.id}} class="custom-control-input"
                            id="check-{{accueilli.nom}}" checked>
                        <label class="custom-control-label" for="check-{{accueilli.nom}}"> {{ accueilli.nom }}</label>
                    </div>
                    {% else %}
                    <div class="custom-control custom-checkbox ">
                        <input type="checkbox" name="check" value={{accueilli.id}} class="custom-control-input"
                            id="check-{{accueilli.nom}}">
                        <label class="custom-control-label" for="check-{{accueilli.nom}}"> {{ accueilli.nom }}</label>
                    </div>
                    {% endif%}
                    {% endfor %}
                </div>
            </div>


            <div class="form-group">
                {{ form.next_action.label(class="form-control-label") }}
                {% if form.next_action.errors %}
                {{ form.next_action(class="form-control form-control-sm is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.next_action.errors %}
                    <span>{{ error }}</span>
                    {% endfor%}
                </div>
                {% else %}
                {{ form.next_action(class="form-control form-control-sm") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.remarques.label(class="form-control-label") }}
                {% if form.remarques.errors %}
                {{ form.remarques(class="form-control form-control-sm is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.remarques.errors %}
                    <span>{{ error }}</span>
                    {% endfor%}
                </div>
                {% else %}
                {{ form.remarques(class="form-control form-control-sm") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="en-tete form-group">
            {{ form.submit(class="btn btn-outline-info")}}
            {% if accueillant %}
            <button type="button" class="btn btn-danger btn-sm m-1 py-0" style="font-size: 0.5em;" data-toggle="modal"
                data-target="#deleteModal">
                <span class="material-icons red600">delete_forever</span>
            </button>
            {% endif %}
        </div>


    </form>
</div>

{% if accueillant %}
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Suppression</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                <form action="{{url_for('accueillants.delete_accueillant', acc_id=accueillant.id)}}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Supprimer">
                </form>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock content %}

flask_app/templates/accueilli_infos.html
{% extends "layout_logged_in.html" %}

{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <div class="form-row">
                <div class="col-10">
                    <legend class="border-bottom mb-4"> {{ legend }}</legend>
                </div>
                {% if accueillant %}
                <div class="col-2">
                    <button type="button" class="btn btn-danger btn-sm m-1 py-0" style="font-size: 0.5em;"
                        data-toggle="modal" data-target="#deleteModal">
                        Supprimer
                    </button>
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.nom.label(class="form-control-label") }}
                {% if form.nom.errors %}
                {{ form.nom(class="form-control form-control-sm is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.nom.errors %}
                    <span>{{ error }}</span>
                    {% endfor%}
                </div>
                {% else %}
                {{ form.nom(class="form-control form-control-sm") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.tel.label(class="form-control-label") }}
                {% if form.tel.errors %}
                {{ form.tel(class="form-control form-control-sm is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.tel.errors %}
                    <span>{{ error }}</span>
                    {% endfor%}
                </div>
                {% else %}
                {{ form.tel(class="form-control form-control-sm") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-sm is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor%}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-sm") }}
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.remarques.label(class="form-control-label") }}
                {% if form.remarques.errors %}
                {{ form.remarques(class="form-control form-control-sm is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.remarques.errors %}
                    <span>{{ error }}</span>
                    {% endfor%}
                </div>
                {% else %}
                {{ form.remarques(class="form-control form-control-sm") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info")}}
        </div>

    </form>
</div>

{% if accueillant %}
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Suppression</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                <!-- To do -> check for the route : delete_accueilli -->
                <form action="{{url_for('accueillants.delete_accueillant', acc_id=accueillant.id)}}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Supprimer">
                </form>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock content %}

flask_app/templates/index.html
{% extends "layout_not_logged_in.html" %}

{% block content %}
<div class="front-page">
    <h1> Site de coordination de l'Ouvre Porte </h1>
    <img src="{{ url_for('static', filename='assets/logo.jpg')}}">
</div>
{% endblock content %}

flask_app/templates/liste_boucles.html
{% extends "layout_logged_in.html" %}

{% block content %}
<h1>Liste des boucles d'accueil</h1>
{% for acc in accueillis %}
<div class='mt-4'>
    <div id="{{ acc.id }}" class="wrapper col-md-12 col-lg-6">
        <article class="media-custom content-section ">
            <div class="media-body">
                <!-- En tête -->
                <div class="en-tete row">
                    <h3 class="article-title "> <span class="title-custom"> Boucle d'accueil de {{ acc.nom }} </span>
                    </h3>
                    <div class="">
                        <a href="{{ url_for('boucles_accueil.update_accueilli', acc_id=acc.id) }}"
                            class="btn btn-warning btn-custom m-1 py-0" role="button" style="font-size: 0.5em;"
                            aria-pressed="true">
                            <i class="material-icons orange600">edit</i>
                        </a>
                        <a href="{{ url_for('boucles_accueil.email_accueilli', acc_id=acc.id) }}"
                            class="btn btn-warning btn-custom m-1 py-0" role="button" style="font-size: 0.5em;"
                            aria-pressed="true">
                            <i class="material-icons orange600 md-18">mail_outline</i>
                        </a>
                    </div>
                </div>

                <!-- Noms des accueillis -->
                <div class="row">
                    <h4>Accueilli par : </h4>
                    {% for a in acc.accueillants %}
                    <button type="button" class="btn btn-outline-info btn-xs m-1 py-0">{{ a.nom }}</button>
                    {% endfor%}
                </div>

                <!-- Infos sur l'accueillant -->
                <div class="infos_accueillants">
                    <button type="button" class="btn btn-info btn-block btn-collapse-custom" data-toggle="collapse"
                        data-target="#info-{{acc.id}}">Informations</button>
                    <div id="info-{{acc.id}}" class="collapse show">
                        <div class="row">
                            <p class="p-custom col-lg-12"><small> <b>Téléphone :</b> {{ acc.tel }}</small></p>
                            <p class="p-custom col-lg-12"><small> <b>Email :</b> {{ acc.email }}</small></p>
                        </div>
                    </div>
                </div>

                <!-- Prochaines actions à mener -->
                <div class="infos_actions">
                    <button type="button" class="btn btn-info btn-block btn-collapse-custom" data-toggle="collapse"
                        data-target="#action-{{acc.id}}">Prochaine action</button>
                    <div id="action-{{acc.id}}" class="collapse show">
                        <small>{{ acc.next_action }}</small>
                    </div>
                </div>
                <!-- Remarques -->
                <div class="infos_remarques">
                    <button type="button" class="btn btn-info btn-block btn-collapse-custom" data-toggle="collapse"
                        data-target="#remarque-{{acc.id}}">Remarques</button>
                    <div id="remarque-{{acc.id}}" class="collapse">
                        <small>{{ acc.remarques }}</small>
                    </div>
                </div>
        </article>
    </div>
</div>
{% endfor %}
{% endblock content %}